<?php

namespace AppBundle\Repository;

/**
 * PlateauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateauRepository extends \Doctrine\ORM\EntityRepository
{
}
